name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  verify-preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm verify:preflight

  build-test:
    runs-on: ubuntu-latest
    needs: verify-preflight
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm ensure-env
      - run: echo "SKIP_VERCEL_BUILD=1" >> .env
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - run: pnpm -w lint
      - run: pnpm -w typecheck
      - run: pnpm -w test
      - run: pnpm docs:lint
      - run: pnpm docs:links
