name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install
      - run: cp .env.example .env
      - run: echo "NAV_V1=on" >> .env
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - run: pnpm verify
